AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Anti-Poaching Patrol Optimizer - AWS SAM Template

Globals:
  Function:
    Timeout: 30
    Runtime: java11
    MemorySize: 512

Resources:
  # DynamoDB Tables
  AntiPoachingMapsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AntiPoachingMaps
      AttributeDefinitions:
        - AttributeName: mapId
          AttributeType: S
      KeySchema:
        - AttributeName: mapId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  PatrolResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PatrolResults
      AttributeDefinitions:
        - AttributeName: resultId
          AttributeType: S
      KeySchema:
        - AttributeName: resultId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # Lambda Functions
  PatrolOptimizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: patrol-optimizer
      Handler: antipoaching.Handler::handleRequest
      CodeUri: ../lambda/patrol-optimizer/target/patrol-optimizer-1.0.0.jar
      Description: Patrol route optimization algorithm
      Events:
        OptimizeApi:
          Type: Api
          Properties:
            Path: /api/optimize
            Method: POST
            RestApiId: !Ref AntiPoachingApi

  DataManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: data-manager
      Handler: antipoaching.Handler::handleRequest
      CodeUri: ../lambda/data-manager/target/data-manager-1.0.0.jar
      Description: DynamoDB data management
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AntiPoachingMapsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref PatrolResultsTable
      Events:
        MapsApi:
          Type: Api
          Properties:
            Path: /api/maps
            Method: ANY
            RestApiId: !Ref AntiPoachingApi
        MapsIdApi:
          Type: Api
          Properties:
            Path: /api/maps/{id}
            Method: ANY
            RestApiId: !Ref AntiPoachingApi
        ResultsApi:
          Type: Api
          Properties:
            Path: /api/results
            Method: ANY
            RestApiId: !Ref AntiPoachingApi
        ResultsIdApi:
          Type: Api
          Properties:
            Path: /api/results/{id}
            Method: ANY
            RestApiId: !Ref AntiPoachingApi

  # API Gateway
  AntiPoachingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"

  # S3 Bucket for Frontend
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'antipoaching-frontend-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

Outputs:
  ApiUrl:
    Description: API Gateway URL
    Value: !Sub 'https://${AntiPoachingApi}.execute-api.${AWS::Region}.amazonaws.com/prod'

  FrontendUrl:
    Description: Frontend S3 Website URL
    Value: !GetAtt FrontendBucket.WebsiteURL

  FrontendBucketName:
    Description: S3 Bucket for frontend deployment
    Value: !Ref FrontendBucket
